// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvspwskluqkqeniwtoqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2c3B3c2tsdXFrcWVuaXd0b3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTMxMjksImV4cCI6MjA2ODg4OTEyOX0.JzU-bMUQM8K-MFER4c2Fybuo_orgSUAzeGSHnzCjeFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});