// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for Supabase configuration
// In Vite, environment variables must be prefixed with VITE_
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables are set
if (!SUPABASE_URL) {
  console.error('❌ VITE_SUPABASE_URL environment variable is required');
  console.error('Please create a .env file in the project root with VITE_SUPABASE_URL=your_supabase_url');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ VITE_SUPABASE_ANON_KEY environment variable is required');
  console.error('Please create a .env file in the project root with VITE_SUPABASE_ANON_KEY=your_anon_key');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public',
  },
  global: {
    headers: {
      'x-client-info': 'markit-social',
    },
  },
});